version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Katmandu
    open-pull-requests-limit: 5
    groups:
      rust-production:
        dependency-type: production
        update-types: [minor, patch]
      rust-development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/crates/findex-tauri"
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Asia/Katmandu
    open-pull-requests-limit: 5
    groups:
      frontend-production:
        dependency-type: production
        update-types: [minor, patch]
      frontend-development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Asia/Katmandu
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns: ["*"]

